<template>
<h1>Animal Rescues In Each Borough</h1>


<h2>Chart by Borough</h2>


<select id="Select" @click="Select()">

<option value="all">All Boroughs</option>
<option value="Manhattan">Manhattan</option>
<option value="Bronx">Bronx</option>
<option value="Brooklyn">Brooklyn</option>
<option value="Queens">Queens</option>
<option value="Staten Island">Staten Island </option>
</select>



</template>